#!/usr/bin/env python3
import argparse
import os

import torch

import npfl138
npfl138.require_version("2526.8")
from npfl138.datasets.morpho_dataset import MorphoDataset

parser = argparse.ArgumentParser()
# These arguments will be set appropriately by ReCodEx, even if you change them.
parser.add_argument("--batch_size", default=10, type=int, help="Batch size.")
parser.add_argument("--epochs", default=5, type=int, help="Number of epochs.")
parser.add_argument("--max_sentences", default=None, type=int, help="Maximum number of sentences to load.")
parser.add_argument("--recodex", default=False, action="store_true", help="Evaluation in ReCodEx.")
parser.add_argument("--rnn", default="LSTM", choices=["LSTM", "GRU"], help="RNN layer type.")
parser.add_argument("--rnn_dim", default=64, type=int, help="RNN layer dimension.")
parser.add_argument("--seed", default=41, type=int, help="Random seed.")
parser.add_argument("--threads", default=1, type=int, help="Maximum number of threads to use.")
parser.add_argument("--we_dim", default=128, type=int, help="Word embedding dimension.")
# If you add more arguments, ReCodEx will keep them with your default values.


class Model(npfl138.TrainableModule):
    def __init__(self, args: argparse.Namespace, train: MorphoDataset.Dataset) -> None:
        super().__init__()
        num_words = len(train.words.string_vocab)
        num_tags = len(train.tags.string_vocab)
        # Create all needed layers.
        # TODO(tagger_we): Create a `torch.nn.Embedding` layer, embedding the word ids
        # from `train.words.string_vocab` to dimensionality `args.we_dim`.
        self._word_embedding = torch.nn.Embedding(
            num_embeddings=num_words,
            embedding_dim=args.we_dim
        )

        # TODO(tagger_we): Create an RNN layer, either `torch.nn.LSTM` or `torch.nn.GRU` depending
        # on `args.rnn`. The layer should be bidirectional (`bidirectional=True`) with
        # dimensionality `args.rnn_dim`. During the model computation, the layer will
        # process the word embeddings generated by the `self._word_embedding` layer,
        # and we will sum the outputs of forward and backward directions.
        assert args.rnn in ["LSTM", "GRU"] 
        if args.rnn == "LSTM":
            rnn_type = torch.nn.LSTM
        else:
            rnn_type = torch.nn.GRU

        self._word_rnn = rnn_type(
            input_size=args.we_dim,
            hidden_size=args.rnn_dim,
            bidirectional=True,
            batch_first=True
        )

        # TODO(tagger_we): Create an output linear layer (`torch.nn.Linear`) processing the RNN output,
        # producing logits for tag prediction; `train.tags.string_vocab` is the tag vocabulary.
        self._output_layer = torch.nn.Linear(args.rnn_dim, num_tags)


    def forward(self, word_ids: torch.Tensor) -> torch.Tensor:
        # TODO: Start by embedding the `word_ids` using the word embedding layer.
        hidden = self._word_embedding(word_ids)  # This is now a sequence of word vectors
        # TODO: Process the embedded words through the RNN layer. Because the sentences
        # have different length, you have to use `torch.nn.utils.rnn.pack_padded_sequence`
        # to construct a variable-length `PackedSequence` from the input. You need to compute
        # the length of each sentence in the batch (by counting non-`MorphoDataset.PAD` tokens);
        # note that these lengths must be on CPU, so you might need to use the `.cpu()` method.
        # Finally, also pass `batch_first=True` and `enforce_sorted=False` to the call.
        lengths = (word_ids != MorphoDataset.PAD).sum(dim=1).cpu()
        packed = torch.nn.utils.rnn.pack_padded_sequence(
            hidden, lengths, batch_first=True, enforce_sorted=False,
        )

        # TODO: Pass the `PackedSequence` through the RNN, choosing the appropriate output.
        packed, _ = self._word_rnn(packed)

        # TODO: Unpack the RNN output using the `torch.nn.utils.rnn.pad_packed_sequence` with
        # `batch_first=True` argument. Then sum the outputs of forward and backward directions.
        hidden, _ = torch.nn.utils.rnn.pad_packed_sequence(packed, batch_first=True, total_length=lengths.max().item())
        # TODO: Pass the RNN output through the output layer. Such an output has a shape
        # `[batch_size, sequence_length, num_tags]`, but the loss and the metric expect
        # the `num_tags` dimension to be in front (`[batch_size, num_tags, sequence_length]`),
        # so you need to reorder the dimensions.
        forward_out, backward_out = hidden.chunk(2, dim=-1)
        hidden = forward_out + backward_out
 
        hidden = self._output_layer(hidden)
        hidden = hidden.transpose(1, 2)
        return hidden

    def compute_loss(self, y_pred: torch.Tensor, y_true: torch.Tensor, word_ids: torch.Tensor) -> torch.Tensor:
        # TODO: Compute the loss as the negative log-likelihood of the gold data `y_true`.
        # The computation must process the whole batch at once.
        # - Start by computing the log probabilities of the predictions using the `log_softmax` method.
        # - Compute the alphas according to the CTC algorithm.
        # - Then, you need to take the appropriate alpha for every batch example (using the corresponding
        #   lengths of `y_pred` and also `y_true`) and compute the loss from it.
        # - The losses of the individual examples should be divided by the length of the
        #   target sequence (excluding padding; use 1 if the target sequence is empty).
        #   - This is because we want to compute averages per logit; the `torch.nn.CTCLoss` does
        #     exactly the same when `reduction="mean"` (the default) is used.
        # - Finally, return the mean of the resulting losses.
        #
        # Several comments:
        # - You can add numbers represented in log space using `torch.logsumexp`/`torch.logaddexp`.
        # - With a slight abuse of notation, use `MorphoDataset.PAD` as the blank label in the CTC algorithm
        #   because `MorphoDataset.PAD` is never a valid output tag.
        # - During the computation, I use `-1e9` as the representation of negative infinity; using
        #   `-torch.inf` did not work for me because some operations were not well defined.
        # - During the loss computation, in some cases the target sequence cannot be produced at all.
        #   In that case return 0 as the loss (the same behaviour as passing `zero_infinity=True`
        #   to `torch.nn.CTCLoss`).
        # - During development, you can compare your outputs to the outputs of `torch.nn.CTCLoss`
        #   (with `reduction="none"` you can compare individual batch examples; in that case,
        #   the normalization by the target sequence lengths is not performed).  However, in ReCodEx,
        #   `torch.nn.CTCLoss` is not available.
        log_probs = y_pred.log_softmax(1).permute(2, 0, 1)
        T, B, C = log_probs.shape

        input_lengths = (word_ids != MorphoDataset.PAD).sum(dim=1)
        target_lengths = (y_true != MorphoDataset.PAD).sum(dim=1)
        S_max = y_true.shape[1]
        ES = 2 * S_max + 1

        extended = torch.full((B, ES), MorphoDataset.PAD, dtype=torch.long, device=y_pred.device)
        extended[:, 1::2] = y_true
        extended_lengths = 2 * target_lengths + 1

        extended_3d = extended.unsqueeze(0).expand(T, B, ES) 
        log_probs_ext = torch.gather(log_probs, 2, extended_3d)

        can_skip = torch.zeros(B, ES, dtype=torch.bool, device=y_pred.device)
        can_skip[:, 2:] = (extended[:, 2:] != MorphoDataset.PAD) & (extended[:, 2:] != extended[:, :-2])  

        # alpha 값 계산
        alpha = torch.full((T, B, ES), -1e9, device=y_pred.device)
        alpha[0, :, 0] = log_probs_ext[0, :, 0] 
        if ES >= 2:
            alpha[0, :, 1] = torch.where(
                target_lengths >= 1,
                log_probs_ext[0, :, 1],
                torch.tensor(-1e9, device=y_pred.device)
            )
        for t in range(1, T):
            new_alpha = alpha[t-1].clone()

            from_prev = torch.full((B, ES), -1e9, device=y_pred.device)
            from_prev[:, 1:] = alpha[t-1, :, :-1]
            new_alpha = torch.logaddexp(new_alpha, from_prev)

            from_skip = torch.full((B, ES), -1e9, device=y_pred.device)
            from_skip[:, 2:] = alpha[t-1, :, :-2]
            from_skip = torch.where(can_skip, from_skip,
                                    torch.tensor(-1e9, device=y_pred.device))
            new_alpha = torch.logaddexp(new_alpha, from_skip)

            alpha[t] = new_alpha + log_probs_ext[t]

        last_t = (input_lengths - 1).clamp(min=0)
        last_t_3d = last_t.view(1, B, 1).expand(1, B, ES)
        alpha_final = alpha.gather(0, last_t_3d).squeeze(0)

        idx_end_blank = (extended_lengths - 1).clamp(min=0)
        idx_end_label = (extended_lengths - 2).clamp(min=0)

        log_p_blank = alpha_final.gather(1, idx_end_blank.unsqueeze(1)).squeeze(1)

        log_p_label = torch.full((B,), -1e9, device=y_pred.device)
        non_empty = target_lengths > 0
        if non_empty.any():
            log_p_label[non_empty] = alpha_final[non_empty].gather(
                1, idx_end_label[non_empty].unsqueeze(1)
            ).squeeze(1)

        log_p = torch.logaddexp(log_p_blank, log_p_label)
        norm = target_lengths.float().clamp(min=1)
        losses = -log_p / norm

        losses = torch.where(
            torch.isinf(losses) | torch.isnan(losses) | (log_p < -1e8),
            torch.zeros_like(losses),
            losses
        )

        return losses.mean()


    def ctc_decoding(self, logits: torch.Tensor, word_ids: torch.Tensor) -> list[torch.Tensor]:
        # TODO: Implement greedy CTC decoding algorithm. The result should be a list of
        # decoded tag sequences, each sequence (batch example) with appropriate length
        # (i.e., at this point we do not pad the predictions in the batch to the same length).
        #
        # The greedy algorithm should, for every batch example:
        # - consider only the predictions corresponding to valid words (i.e., not the padding ones);
        # - compute the most probable extended label for every one of them;
        # - remove repeated labels;
        # - finally remove the blank labels (which are `MorphoDataset.PAD` in our case).

        results = []
        tokens = logits.argmax(dim=1)   
        B = logits.shape[0]
        for b in range(B):
            valid = tokens[b][word_ids[b] != MorphoDataset.PAD]
            mask = torch.cat([
                torch.tensor([True], device=logits.device),
                valid[1:] != valid[:-1]
            ])
            deduped = valid[mask]
            decoded = deduped[deduped != MorphoDataset.PAD]

            results.append(decoded) 
        return results

    def compute_metrics(
        self, y_pred: torch.Tensor, y_true: torch.Tensor, word_ids: torch.Tensor
    ) -> dict[str, torch.Tensor]:
        # TODO: Compute predictions using the `ctc_decoding`.
        predictions = self.ctc_decoding(y_pred, word_ids)

        self.metrics["edit_distance"].update(predictions, y_true)
        return self.metrics

    def predict_step(self, xs):
        with torch.no_grad():
            # Perform constrained decoding.
            yield from self.ctc_decoding(self.forward(*xs), *xs)


class TrainableDataset(npfl138.TransformedDataset):
    def transform(self, example):
        # TODO(tagger_we): Construct a single example, each consisting of the following pair:
        # - a PyTorch tensor of integer ids of input words as input,
        # - a PyTorch tensor of integer tag ids as targets.
        # To create the ids, use `string_vocab` of `self.dataset.words` and `self.dataset.tags`.
        #
        # TODO: However, compared to `tagger_we`, keep in the target sequence only the tags
        # starting with "B-" (before remapping them to ids).

        ### 이건 또 뭔소리래 ###

        word_ids = torch.tensor(
            self.dataset.words.string_vocab.indices(example["words"]),
            dtype=torch.int64
        )
        filtered_tags = [tag for tag in example["tags"] if tag.startswith("B-")]

        tag_ids = torch.tensor(
            self.dataset.tags.string_vocab.indices(filtered_tags),
            dtype=torch.int64
        )
        return word_ids, tag_ids

    def collate(self, batch):
        # Construct a single batch, where `batch` is a list of examples
        # generated by `transform`.
        word_ids, tag_ids = zip(*batch)
        # TODO(tagger_we): Combine `word_ids` into a single tensor, padding shorter
        # sequences to length of the longest sequence in the batch with zeros
        # using `torch.nn.utils.rnn.pad_sequence` with `batch_first=True` argument.
        word_ids = torch.nn.utils.rnn.pad_sequence(word_ids, batch_first=True, padding_value=0)

        # TODO(tagger_we): Process `tag_ids` analogously to `word_ids`.
        tag_ids = torch.nn.utils.rnn.pad_sequence(tag_ids, batch_first=True, padding_value=0)
        return word_ids, tag_ids


def main(args: argparse.Namespace) -> dict[str, float]:
    # Set the random seed and the number of threads.
    npfl138.startup(args.seed, args.threads)
    npfl138.global_keras_initializers()

    # Load the data.
    morpho = MorphoDataset("czech_cnec", max_sentences=args.max_sentences)

    # Prepare the data for training.
    train = TrainableDataset(morpho.train).dataloader(batch_size=args.batch_size, shuffle=True)
    dev = TrainableDataset(morpho.dev).dataloader(batch_size=args.batch_size)

    # Create the model and train.
    model = Model(args, morpho.train)

    model.configure(
        # TODO(tagger_we): Create the Adam optimizer.
        optimizer=torch.optim.Adam(model.parameters()),
        # We compute the loss using `compute_loss` method, so no `loss` is passed here.
        metrics={
            # TODO: Create `npfl138.metrics.EditDistance` evaluating CTC greedy decoding, passing
            # `ignore_index=morpho.PAD`.
            "edit_distance": npfl138.metrics.EditDistance(ignore_index=morpho.PAD),
        },
        logdir=npfl138.format_logdir("logs/{file-}{timestamp}{-config}", **vars(args)),
    )

    logs = model.fit(train, dev=dev, epochs=args.epochs)

    # Return all metrics for ReCodEx to validate.
    return {metric: value for metric, value in logs.items()}


if __name__ == "__main__":
    main_args = parser.parse_args([] if "__file__" not in globals() else None)
    main(main_args)
