#!/usr/bin/env python3
import argparse

import torch
import torchmetrics

import npfl138
npfl138.require_version("2526.8")
from npfl138.datasets.morpho_dataset import MorphoDataset

parser = argparse.ArgumentParser()
# These arguments will be set appropriately by ReCodEx, even if you change them.
parser.add_argument("--batch_size", default=10, type=int, help="Batch size.")
parser.add_argument("--epochs", default=5, type=int, help="Number of epochs.")
parser.add_argument("--label_smoothing", default=0.0, type=float, help="Label smoothing.")
parser.add_argument("--max_sentences", default=None, type=int, help="Maximum number of sentences to load.")
parser.add_argument("--recodex", default=False, action="store_true", help="Evaluation in ReCodEx.")
parser.add_argument("--rnn", default="LSTM", choices=["LSTM", "GRU"], help="RNN layer type.")
parser.add_argument("--rnn_dim", default=64, type=int, help="RNN layer dimension.")
parser.add_argument("--seed", default=219, type=int, help="Random seed.")
parser.add_argument("--show_predictions", default=False, action="store_true", help="Show predicted tag sequences.")
parser.add_argument("--threads", default=1, type=int, help="Maximum number of threads to use.")
parser.add_argument("--we_dim", default=128, type=int, help="Word embedding dimension.")
# If you add more arguments, ReCodEx will keep them with your default values.


class Model(npfl138.TrainableModule):
    def __init__(self, args: argparse.Namespace, train: MorphoDataset.Dataset) -> None:
        super().__init__()
        self._show_predictions = args.show_predictions
        num_words = len(train.words.string_vocab)
        self.num_tags = len(train.tags.string_vocab)


        # TODO: Compute the transition matrix `A` of shape `[num_tags, num_tags]`, so
        # that `A[i, j]` is 0/1 depending on whether the tag `j` is allowed to follow
        # the tag `i` (according to our BIO encoding; not necessarily in the data).
        # The tag strings can be obtained by calling `list(train.tags.string_vocab)`.
        A = torch.zeros(self.num_tags, self.num_tags)
        for i, from_tag in enumerate(train.tags.string_vocab):
            for j, to_tag in enumerate(train.tags.string_vocab):
                if to_tag == 'O' or to_tag.startswith('B-'):
                    A[i, j] = 1
                elif to_tag.startswith('I-'):
                    if from_tag[2:] == to_tag[2:]:
                        A[i, j] = 1

        # The following call will create `self._A` and it will become part of the object state.
        self.register_buffer("_A", A)

        # Precompute log-space transition matrix: 0 for valid, -inf for invalid.
        log_A = torch.where(A.bool(), torch.zeros_like(A), torch.full_like(A, float('-inf')))
        self.register_buffer("_log_A", log_A)

        # Precompute start mask: sequence cannot begin with an I- tag.
        # This is equivalent to transitions from a virtual "O" tag at position -1.
        tag_list = list(train.tags.string_vocab)
        o_idx = tag_list.index('O')
        start_mask = torch.where(A[o_idx].bool(),
                                 torch.zeros(self.num_tags),
                                 torch.full((self.num_tags,), float('-inf')))
        self.register_buffer("_start_mask", start_mask)

        # Create all needed layers.
        # TODO(tagger_we): Create a `torch.nn.Embedding` layer, embedding the word ids
        # from `train.words.string_vocab` to dimensionality `args.we_dim`.
        self._word_embedding = torch.nn.Embedding(
            num_embeddings=num_words,
            embedding_dim=args.we_dim
        )
        # TODO(tagger_we): Create an RNN layer, either `torch.nn.LSTM` or `torch.nn.GRU` depending
        # on `args.rnn`. The layer should be bidirectional (`bidirectional=True`) with
        # dimensionality `args.rnn_dim`. During the model computation, the layer will
        # process the word embeddings generated by the `self._word_embedding` layer,
        # and we will sum the outputs of forward and backward directions.
        assert args.rnn in ["LSTM", "GRU"] 
        if args.rnn == "LSTM":
            self._word_rnn = torch.nn.LSTM(
                input_size=args.we_dim,
                hidden_size=args.rnn_dim,
                bidirectional=True,
                batch_first=True
            )
        else:
            self._word_rnn = torch.nn.GRU(
                input_size=args.we_dim,
                hidden_size=args.rnn_dim,
                bidirectional=True,
                batch_first=True
            )

        # TODO(tagger_we): Create an output linear layer (`torch.nn.Linear`) processing the RNN output,
        # producing logits for tag prediction; `train.tags.string_vocab` is the tag vocabulary.
        self._output_layer = torch.nn.Linear(args.rnn_dim, self.num_tags)

    def forward(self, word_ids: torch.Tensor) -> torch.Tensor:
        # TODO: Start by embedding the `word_ids` using the word embedding layer.
        hidden = self._word_embedding(word_ids)  

        # TODO: Process the embedded words through the RNN layer. Because the sentences
        # have different length, you have to use `torch.nn.utils.rnn.pack_padded_sequence`
        # to construct a variable-length `PackedSequence` from the input. You need to compute
        # the length of each sentence in the batch (by counting non-`MorphoDataset.PAD` tokens);
        # note that these lengths must be on CPU, so you might need to use the `.cpu()` method.
        # Finally, also pass `batch_first=True` and `enforce_sorted=False` to the call.
        lengths = (word_ids != MorphoDataset.PAD).sum(dim=1).cpu()
        packed = torch.nn.utils.rnn.pack_padded_sequence(
            hidden, lengths, batch_first=True, enforce_sorted=False,
        )

        # TODO: Pass the `PackedSequence` through the RNN, choosing the appropriate output.
        packed, _ = self._word_rnn(packed)

        # TODO: Unpack the RNN output using the `torch.nn.utils.rnn.pad_packed_sequence` with
        # `batch_first=True` argument. Then sum the outputs of forward and backward directions.
        hidden, _ = torch.nn.utils.rnn.pad_packed_sequence(packed, batch_first=True, total_length=lengths.max().item())
        # TODO: Pass the RNN output through the output layer. Such an output has a shape
        # `[batch_size, sequence_length, num_tags]`, but the loss and the metric expect
        # the `num_tags` dimension to be in front (`[batch_size, num_tags, sequence_length]`),
        # so you need to reorder the dimensions.
        forward_out, backward_out = hidden.chunk(2, dim=-1)
        hidden = forward_out + backward_out
 
        hidden = self._output_layer(hidden)
        hidden = hidden.transpose(1, 2)
        return hidden

    def constrained_decoding(self, logits: torch.Tensor, word_ids: torch.Tensor) -> torch.Tensor:
        # logits:   [batch_size, num_tags, seq_len]  (output of forward)
        # word_ids: [batch_size, seq_len]
        batch_size, num_tags, seq_len = logits.shape

        # log_probs[b, t, k] = raw logit for tag k at position t in sentence b.
        log_probs = logits.transpose(1, 2)  # [batch_size, seq_len, num_tags]

        # ── Forward pass (Viterbi) ─────────────────────────────────────────────
        # alpha[b, k]: best cumulative score of any valid path ending at tag k
        #              at the current time step, over all sentences in the batch.
        # t = 0: apply _start_mask so that I- tags can never be the first tag.
        alpha = log_probs[:, 0, :] + self._start_mask  # [batch_size, num_tags]

        # beta[b, t, k]: argmax previous tag when the best path arrives at tag k
        #                at position t — used for traceback.
        beta = torch.zeros(batch_size, seq_len, num_tags, dtype=torch.long, device=logits.device)

        # Only the loop over the sequence length is sequential.
        # All batch and tag operations inside are vectorized.
        for t in range(1, seq_len):
            # scores[b, i, j] = alpha[b, i] + log_A[i, j]
            # Expand: alpha [batch, num_tags, 1] + _log_A [1, num_tags, num_tags]
            scores = alpha.unsqueeze(2) + self._log_A.unsqueeze(0)  # [batch, num_tags, num_tags]

            # For each (b, j): best predecessor tag i and the corresponding score.
            best_scores, best_prev = scores.max(dim=1)  # both [batch_size, num_tags]

            beta[:, t, :] = best_prev
            alpha = best_scores + log_probs[:, t, :]  # [batch_size, num_tags]

        # ── Backward pass (traceback) ──────────────────────────────────────────
        tags = torch.zeros(batch_size, seq_len, dtype=torch.long, device=logits.device)
        tags[:, -1] = alpha.argmax(dim=1)  # [batch_size] — best final tag

        for t in range(seq_len - 2, -1, -1):
            # beta[:, t+1, tags[:, t+1]] — for each b, look up the best predecessor
            tags[:, t] = beta[:, t + 1, :].gather(1, tags[:, t + 1].unsqueeze(1)).squeeze(1)

        # ── Replace padding positions with MorphoDataset.PAD ──────────────────
        tags.masked_fill_(word_ids == MorphoDataset.PAD, MorphoDataset.PAD)

        return tags  # [batch_size, seq_len]

    def compute_metrics(self, y_pred, y, word_ids):
        self.metrics["accuracy"].update(y_pred, y)
        if self.training:
            return {"accuracy": self.metrics["accuracy"]}

        # Perform greedy decoding.
        predictions_greedy = y_pred.argmax(dim=1)
        predictions_greedy.masked_fill_(word_ids == MorphoDataset.PAD, MorphoDataset.PAD)
        self.metrics["f1_greedy"].update(predictions_greedy, y)

        # Perform constrained decoding by calling `self.constrained_decoding`
        # on `y_pred` and `word_ids`.
        predictions = self.constrained_decoding(y_pred, word_ids)
        self.metrics["f1_constrained"].update(predictions, y)

        if self._show_predictions:
            for tags in predictions:
                print(*[self.metrics["f1_constrained"]._labels[tag] for tag in tags])

        return self.metrics

    def predict_step(self, xs):
        with torch.no_grad():
            # Perform constrained decoding and trim the padding tags from the predictions.
            for item in self.constrained_decoding(self.forward(*xs), *xs):
                yield item[item != MorphoDataset.PAD]


class TrainableDataset(npfl138.TransformedDataset):
    def transform(self, example):
        # TODO(tagger_we): Construct a single example, each consisting of the following pair:
        # - a PyTorch tensor of integer ids of input words as input,
        # - a PyTorch tensor of integer tag ids as targets.
        # To create the ids, use `string_vocab` of `self.dataset.words` and `self.dataset.tags`.
        word_ids = torch.tensor(
            self.dataset.words.string_vocab.indices(example["words"]),
            dtype=torch.int64
        )
        tag_ids = torch.tensor(
            self.dataset.tags.string_vocab.indices(example["tags"]),
            dtype=torch.int64
        )
        return word_ids, tag_ids

    def collate(self, batch):
        # Construct a single batch, where `batch` is a list of examples
        # generated by `transform`.
        word_ids, tag_ids = zip(*batch)
        # TODO: Combine `word_ids` into a single tensor, padding shorter
        # sequences to length of the longest sequence in the batch with zeros
        # using `torch.nn.utils.rnn.pad_sequence` with `batch_first=True` argument.
        word_ids = torch.nn.utils.rnn.pad_sequence(word_ids, batch_first=True, padding_value=0)
        # TODO: Process `tag_ids` analogously to `word_ids`.
        tag_ids = torch.nn.utils.rnn.pad_sequence(tag_ids, batch_first=True, padding_value=0)
        return word_ids, tag_ids


def main(args: argparse.Namespace) -> dict[str, float]:
    # Set the random seed and the number of threads.
    npfl138.startup(args.seed, args.threads)
    npfl138.global_keras_initializers()

    # Load the data.
    morpho = MorphoDataset("czech_cnec", max_sentences=args.max_sentences)

    # Prepare the data for training.
    train = TrainableDataset(morpho.train).dataloader(batch_size=args.batch_size, shuffle=True)
    dev = TrainableDataset(morpho.dev).dataloader(batch_size=args.batch_size)

    # Create the model and train.
    model = Model(args, morpho.train)

    model.configure(
        # TODO(tagger_we): Create the Adam optimizer.
        optimizer=torch.optim.Adam(model.parameters()),
        # TODO: Use `torch.nn.CrossEntropyLoss` to instantiate the loss function.
        # Pass `ignore_index=morpho.PAD` to the constructor to ignore padding tags
        # during loss computation; also pass `label_smoothing=args.label_smoothing`.
        loss=torch.nn.CrossEntropyLoss(
            ignore_index=morpho.PAD,
            label_smoothing=args.label_smoothing,
        ),
        metrics={
            # TODO(tagger_we): Create a `torchmetrics.Accuracy` metric, passing "multiclass" as
            # the first argument, `num_classes` set to the number of unique tags, and
            # again `ignore_index=morpho.PAD` to ignore the padded tags.
            "accuracy": torchmetrics.Accuracy(
                "multiclass",
                num_classes=len(morpho.train.tags.string_vocab),
                ignore_index=morpho.PAD
            ),
            # TODO: Create a `npfl138.metrics.BIOEncodingF1Score` for constrained decoding and also
            # for greedy decoding, passing both a `list(morpho.train.tags.string_vocab)`
            # and `ignore_index=morpho.PAD`.
            "f1_constrained": npfl138.metrics.BIOEncodingF1Score(
                list(morpho.train.tags.string_vocab),
                ignore_index=morpho.PAD
            ),
            "f1_greedy": npfl138.metrics.BIOEncodingF1Score(
                list(morpho.train.tags.string_vocab),
                ignore_index=morpho.PAD
            )
        },
        logdir=npfl138.format_logdir("logs/{file-}{timestamp}{-config}", **vars(args)),
    )

    logs = model.fit(train, dev=dev, epochs=args.epochs)

    # Return development metrics for ReCodEx to validate.
    return {metric: value for metric, value in logs.items() if metric.startswith("dev:")}


if __name__ == "__main__":
    main_args = parser.parse_args([] if "__file__" not in globals() else None)
    main(main_args)
